version: "2"
services:
   mongodb:
    image : mongo:4.0
    container_name: mongodb
    environment:
     - PUID=1000
     - PGID=1000
    volumes:
     - ./data/mongodb:/data/db
    ports:
     - 27017:27017
    restart: unless-stopped
    